type = "directrequest"
schemaVersion = 1
name = "paypal-job"
maxTaskDuration = "0s"
contractAddress = "0x294e6eC95F11aF23773F10D1E636e0517518101b"
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    fetch        [type=bridge name="paypal-bridge-three" requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"payout_id\\": $(decode_cbor.payout_id)}}"]
    parsePaymentMethod   [type="jsonparse" path="data,paymentMethod" data="$(fetch)"]
    parseTo   [type="jsonparse" path="data,to" data="$(fetch)"]
    parseFrom   [type="jsonparse" path="data,from" data="$(fetch)"]
    parseAmount   [type="jsonparse" path="data,amount" data="$(fetch)"]
    parseTransactionId   [type="jsonparse" path="data,transactionId" data="$(fetch)"]
    parseCurrency   [type="jsonparse" path="data,currency" data="$(fetch)"]
    parsePaymentTime   [type="jsonparse" path="data,paymentTime" data="$(fetch)"]
    parseAccountId   [type="jsonparse" path="data,accountId" data="$(fetch)"]
    parseEventName   [type="jsonparse" path="data,eventName" data="$(fetch)"]
    parseOrganisationId   [type="jsonparse" path="data,organisationId" data="$(fetch)"]
    encode_data  [type=ethabiencode abi="(bytes32 requestId,string info)" data="{\\"requestId\\": $(decode_log.requestId),\\"info\\": $(parse) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"]
    submit_tx    [type=ethtx to="0x294e6eC95F11aF23773F10D1E636e0517518101b" data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parsePaymentMethod -> parseTo -> parseFrom -> parseAmount -> parseTransactionId -> parseCurrency -> parsePaymentTime -> parseAccountId -> parseEventName -> parseOrganisationId -> encode_data -> encode_tx -> submit_tx
"""
