type = "directrequest"
schemaVersion = 1
name = "paypal-bridge" #  TODO Pick a Job name
maxTaskDuration = "0s"
contractAddress = " #### INSERT YOURS HERE ####  " # TODO Update to your Operator / Oracle contract here and in submit_tx.
minContractPaymentLinkJuels = "0"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]

    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    fetch        [type=bridge name="numbers-bridge" requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"payout_id\\": $(decode_cbor.payout_id) }}"]
    parse_id = [type=jsonparse path="data,result,id" data="$(fetch)"]
    parse_paymentMethod = [type=jsonparse path="data,result,paymentMethod" data="$(fetch)"]
    parse_to = [type=jsonparse path="data,result,to" data="$(fetch)"]
    parse_from = [type=jsonparse path="data,result,from" data="$(fetch)"]
    parse_amount = [type=jsonparse path="data,result,amount" data="$(fetch)"]
    parse_transactionId = [type=jsonparse path="data,result,transactionId" data="$(fetch)"]
    parse_currency = [type=jsonparse path="data,result,currency" data="$(fetch)"]
    parse_paymentTime = [type=jsonparse path="data,result,paymentTime" data="$(fetch)"]
    parse_accountId = [type=jsonparse path="data,result,accountId" data="$(fetch)"]
    parse_eventName = [type=jsonparse path="data,result,eventName" data="$(fetch)"]
    parse_organisationId = [type=jsonparse path="data,result,organisationI" data="$(fetch)"]
    encode_data  [type=ethabiencode 
                    abi="(bytes32 requestId,string info)" 
                    data="{\\"requestId\\": $(decode_log.requestId),\\"id\\:"$(parse_id),\\"paymentMethod\\:"$(parse_paymentMethod),\\"to\\:"$(parse_to),\\"from\\:"$(parse_from),\\"amount\\:"$(parse_amount),\\"transactionId\\:"$(parse_transactionId),\\"currency\\:"$(parse_currency),\\"paymentTime\\:"$(parse_paymentTime),\\"accountId\\:"$(parse_accountId),\\"eventName\\:"$(parse_eventName),\\"organisationI\\:"$(parse_organisationI),
 }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"]
    submit_tx    [type=ethtx to=" #### INSERT YOURS HERE #### " data="$(encode_tx)"]

    decode_log -> decode_cbor -> fetch -> parse -> encode_data -> encode_tx -> submit_tx
"""
